'use server'

import { db } from '@/lib/db'
import {
  accounts,
  categories,
  groups,
  transactions,
  incomes,
  incomeSources,
  monthlySnapshots,
} from '@/db/schema'
import { eq, and, isNull } from 'drizzle-orm'

// Converts a date to "YYYY-M" string — avoids millisecond/timezone precision issues
// when comparing months stored in Postgres vs dates generated by the parser.
function toMonthKey(d: Date | string | unknown): string {
  const date = d instanceof Date ? d : new Date(String(d))
  return `${date.getUTCFullYear()}-${date.getUTCMonth()}`
}
import { parseGastosWorkbook } from './parsers/gastos'
import { parseSuperchicWorkbook } from './parsers/superchic'
import { createClient } from '@/lib/supabase/server'

async function requireAuth() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) throw new Error('No autorizado')
  return user
}

export type ImportResult = {
  inserted: number
  skipped: number
  warnings: string[]
}

export async function importGastos(formData: FormData): Promise<ImportResult> {
  await requireAuth()

  const file = formData.get('file') as File
  if (!file) throw new Error('No se recibió ningún archivo')

  const buffer = Buffer.from(await file.arrayBuffer())
  const { transactions: rows, warnings } = parseGastosWorkbook(buffer)
  if (rows.length === 0) return { inserted: 0, skipped: 0, warnings }

  // Bulk upsert categories
  const uniqueCategoryNames = [...new Set(rows.map(r => r.categoryName))]
  const existingCats = await db
    .select({ id: categories.id, name: categories.name })
    .from(categories)
    .where(isNull(categories.archivedAt))
  const catIdByName = new Map(existingCats.map(c => [c.name, c.id]))
  const newCatNames = uniqueCategoryNames.filter(n => !catIdByName.has(n))
  if (newCatNames.length > 0) {
    const created = await db
      .insert(categories)
      .values(newCatNames.map(name => ({ name })))
      .returning({ id: categories.id, name: categories.name })
    created.forEach(c => catIdByName.set(c.name, c.id))
  }

  // Bulk upsert groups
  const uniqueGroupNames = [...new Set(rows.map(r => r.groupName).filter(Boolean))] as string[]
  const existingGrps = await db
    .select({ id: groups.id, name: groups.name })
    .from(groups)
    .where(isNull(groups.archivedAt))
  const grpIdByName = new Map(existingGrps.map(g => [g.name, g.id]))
  const newGrpNames = uniqueGroupNames.filter(n => !grpIdByName.has(n))
  if (newGrpNames.length > 0) {
    const created = await db
      .insert(groups)
      .values(newGrpNames.map(name => ({ name })))
      .returning({ id: groups.id, name: groups.name })
    created.forEach(g => grpIdByName.set(g.name, g.id))
  }

  // Idempotency: fetch existing paidAt timestamps
  const existingTxns = await db
    .select({ paidAt: transactions.paidAt })
    .from(transactions)
  const existingPaidAts = new Set(existingTxns.map(t => t.paidAt.getTime()))

  // Bulk insert only new rows
  const toInsert = rows.filter(r => !existingPaidAts.has(r.paidAt.getTime()))
  if (toInsert.length > 0) {
    await db.insert(transactions).values(
      toInsert.map(r => ({
        amount: String(r.amount),
        paidAt: r.paidAt,
        categoryId: catIdByName.get(r.categoryName) ?? null,
        groupId: r.groupName ? (grpIdByName.get(r.groupName) ?? null) : null,
        description: r.description,
        prescindible: r.prescindible,
      }))
    )
  }

  return { inserted: toInsert.length, skipped: rows.length - toInsert.length, warnings }
}

export async function importSuperchic(formData: FormData): Promise<ImportResult> {
  await requireAuth()

  const file = formData.get('file') as File
  if (!file) throw new Error('No se recibió ningún archivo')

  const buffer = Buffer.from(await file.arrayBuffer())
  const { accounts: parsedAccounts, snapshots, incomes: parsedIncomes, warnings } = parseSuperchicWorkbook(buffer)

  let inserted = 0
  let skipped = 0

  // Upsert accounts (only 9, no need to batch)
  const accountIdByName = new Map<string, string>()
  for (const acc of parsedAccounts) {
    const existing = await db
      .select({ id: accounts.id })
      .from(accounts)
      .where(and(eq(accounts.name, acc.name), isNull(accounts.archivedAt)))
      .limit(1)
    if (existing.length > 0) {
      accountIdByName.set(acc.name, existing[0].id)
    } else {
      const [created] = await db
        .insert(accounts)
        .values({ name: acc.name, gainMode: acc.gainMode, sortOrder: acc.sortOrder })
        .returning({ id: accounts.id })
      accountIdByName.set(acc.name, created.id)
    }
  }

  // Bulk upsert snapshots
  const existingSnaps = await db
    .select({ accountId: monthlySnapshots.accountId, month: monthlySnapshots.month })
    .from(monthlySnapshots)
  const existingSnapKeys = new Set(existingSnaps.map(s => `${s.accountId}|${toMonthKey(s.month)}`))

  const snapsToInsert = snapshots.filter(s => {
    const accountId = accountIdByName.get(s.accountName)
    return accountId && !existingSnapKeys.has(`${accountId}|${toMonthKey(s.month)}`)
  })
  skipped += snapshots.length - snapsToInsert.length

  if (snapsToInsert.length > 0) {
    await db.insert(monthlySnapshots).values(
      snapsToInsert.map(s => ({
        accountId: accountIdByName.get(s.accountName)!,
        month: s.month,
        openingBalance: String(s.openingBalance),
        closingBalance: String(s.closingBalance),
        contributions: String(s.contributions),
        gainManual: s.gainManual != null ? String(s.gainManual) : null,
      }))
    )
    inserted += snapsToInsert.length
  }

  // Bulk upsert income sources
  const uniqueSourceNames = [...new Set(parsedIncomes.map(i => i.sourceNameRaw))]
  const existingSources = await db
    .select({ id: incomeSources.id, name: incomeSources.name })
    .from(incomeSources)
    .where(isNull(incomeSources.archivedAt))
  const sourceIdByName = new Map(existingSources.map(s => [s.name, s.id]))
  const newSourceNames = uniqueSourceNames.filter(n => !sourceIdByName.has(n))
  if (newSourceNames.length > 0) {
    const created = await db
      .insert(incomeSources)
      .values(newSourceNames.map((name, i) => ({ name, sortOrder: existingSources.length + i })))
      .returning({ id: incomeSources.id, name: incomeSources.name })
    created.forEach(s => sourceIdByName.set(s.name, s.id))
  }

  // Bulk upsert incomes
  const existingIncs = await db
    .select({ receivedAt: incomes.receivedAt, amount: incomes.amount, incomeSourceId: incomes.incomeSourceId })
    .from(incomes)
  const existingIncKeys = new Set(
    existingIncs.map(i => `${toMonthKey(i.receivedAt)}|${Number(i.amount).toFixed(2)}|${i.incomeSourceId}`)
  )

  const incsToInsert = parsedIncomes.filter(i => {
    const sourceId = sourceIdByName.get(i.sourceNameRaw)
    return sourceId && !existingIncKeys.has(`${toMonthKey(i.receivedAt)}|${i.amount.toFixed(2)}|${sourceId}`)
  })
  skipped += parsedIncomes.length - incsToInsert.length

  if (incsToInsert.length > 0) {
    await db.insert(incomes).values(
      incsToInsert.map(i => ({
        amount: String(i.amount),
        receivedAt: i.receivedAt,
        budgetMonth: i.budgetMonth,
        incomeSourceId: sourceIdByName.get(i.sourceNameRaw)!,
        description: i.description,
      }))
    )
    inserted += incsToInsert.length
  }

  return { inserted, skipped, warnings }
}
